version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: merch_nft_db
    volumes:
      - ./backup:/home/
    ports:
      - "3306:3306"
